### ISSUE TITLE
Error Try example

### ISSUE THREAD

**Issue by joscani** [Evovest/EvoTrees#2]
I'm get the following error.

```r
model <- evo_train(data_train = data_train, target_train = target_train, params = params)
Error: Error happens in Julia.
MethodError: no method matching EvoTreeRModels(::Symbol, ::Int64, ::Float64, ::Float64, ::Float64, ::Int64, ::Float64, ::Float64, ::Float64, ::Int64, ::Float64, ::Symbol, ::Int64)
```

**Comment by jeremiedb** [comment]
Hi @joscani, thanks for reporting this issue. 
Reason for the error was that I hadn't update the R-package to reflect some refactor to the underlying Julia package. 
I've just the fixes and should now be working (package version 0.9.1). Should be working with EvoTrees.jl v0.9.0+.

Let me know if it encounter any further issue!

**Comment by joscani** [comment]
Thanks . I'll try tomorrow. 
And I'm interested in how to create R packages calling Julia package

**Comment by joscani** [comment]
uhmm, error installing from github

```bash 
> devtools::install_github("Evovest/EvoTrees")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo Evovest/EvoTrees@HEAD
tar (child): gzip: No se puede exec: No existe el archivo o el directorio
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
tar (child): gzip: No se puede exec: No existe el archivo o el directorio
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
Error: Failed to install 'EvoTrees' from GitHub:
  length(file_list) > 0 is not TRUE
Además: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘/bin/tar -xf '/tmp/RtmpQBA4ng/file18064d4b6055.tar.gz' -C '/tmp/RtmpQBA4ng/remotes18065efe373c'’ returned error code 2
2: In system(cmd, intern = TRUE) :
  comando ejecutado '/bin/tar -tf '/tmp/RtmpQBA4ng/file18064d4b6055.tar.gz'' tiene estatus 2
```

**Comment by jeremiedb** [comment]
On what version of R are you?
Could you validate there is no firewall blocking access?
I just had a successful install using the `devtools::install_github` command.

**Comment by joscani** [comment]
uhm.. It seems I have problem with tar. something has changed from yesterday in my linux system. Thanks in advance

**Comment by joscani** [comment]
It works now. It was an error on my side. Thanks for all. And evotrees is a great library in julia.
